#include <iostream>
#include <string>
#include <time.h>

#include "Scene.h"
#include "Raytracer.h"

using std::string;
using std::cout;
using std::cin;

string testMenu();
void testPpmOutput();
void save_image(int Width, int Height, const char* fname, unsigned char* pixels);

int main(int argc, char* argv[])
{
	string filename;

	// If no test was given as an input, display the tests for the user to choose from
	if (argc == 1)
		filename = testMenu();

	// Otherwise, load the test given
	else
		filename = argv[1];
	
	// Create a scene from the test file
	Scene scene(filename);

	// Create a raytracer form the generated scene
	Raytracer raytracer(&scene);

	std::cout << "Starting to calculate raytrace...\n";
	
	// Perform the raytrace
	raytracer.Raytrace();

	// Output image from data generated by the raytracer
	save_image(scene.GetWidth(), scene.GetHeight(), scene.GetOutputName().c_str(), raytracer.GetData());

	return 0;
}

void save_image(int Width, int Height, const char* fname, unsigned char* pixels) {
	FILE *fp;
	const int maxVal=255; 

	printf("Saving image %s: %d x %d\n", fname,Width,Height);

	std::string ouputName = "Output/";
	ouputName += fname;

	fp = fopen(ouputName.c_str(),"wb");
	if (!fp) {
		printf("Unable to open file '%s'\n",fname);
		return;
	}
	fprintf(fp, "P6\n");
	fprintf(fp, "%d %d\n", Width, Height);
	fprintf(fp, "%d\n", maxVal);

	for(int j = 0; j < Height; j++) {
		fwrite(&pixels[j*Width*3], 3,Width,fp);
	}

	fclose(fp);
}

string testMenu()
{
	string ambient = "testAmbient";
	string background = "testBackground";
	string behind = "testBehind";
	string diffuse = "testDiffuse";
	string illum = "testIllum";
	string imgPlane = "testImgPlane";
	string intersction = "testIntersection";
	string parsing = "testParsing";
	string reflection = "testReflection";
	string sample = "testSample";
	string shadow = "testShadow";
	string specular = "testSpecular";
	
	// Display tests
	cout << "Choose a test (1-12): \n";
	cout << "1: " << ambient << "\n";
	cout << "2: " << background << "\n";
	cout << "3: " << behind << "\n";
	cout << "4: " << diffuse << "\n";
	cout << "5: " << illum << "\n";
	cout << "6: " << imgPlane << "\n";
	cout << "7: " << intersction << "\n";
	cout << "8: " << parsing << "\n";
	cout << "9: " << reflection << "\n";
	cout << "10: " << sample << "\n";
	cout << "11: " << shadow << "\n";
	cout << "12: " << specular << "\n";

	// Get user's choice
	int choice;
	cin >> choice;

	// Assign correct filename.
	string filename = "tests/";
	switch (choice)
	{
	case 1:
		filename.append(ambient);
		break;
	case 2:
		filename.append(background);
		break;
	case 3:
		filename.append(behind);
		break;
	case 4:
		filename.append(diffuse);
		break;
	case 5:
		filename.append(illum);
		break;
	case 6:
		filename.append(imgPlane);
		break;
	case 7:
		filename.append(intersction);
		break;
	case 8:
		filename.append(parsing);
		break;
	case 9:
		filename.append(reflection);
		break;
	case 10:
		filename.append(sample);
		break;
	case 11:
		filename.append(shadow);
		break;
	case 12:
		filename.append(specular);
		break;
	}

	return filename.append(".txt");
}